backend = "openxr"

## This is the configuration file for index_camera_passthrough.
## This file should live at ~/.config/index_camera_passthrough.toml

## camera device to use. auto detect if not set
camera_device = ""

## to open and close the overlay, you need to press two buttons on your
## controller at the same time. which buttons are used can be configured
## in SteamVR controller bindings

## how long does the button need to be held before the overlay open,
## closing the overlay is always instantaneous
open_delay = "0s"

# [overlay]
# ## z order of the overlay. higher z order means the overlay is on top of
# ## other overlays. Not supported on all backends, supported on OpenXR.
# z_order = 0

[position]
## how will the overlay be positioned.
## possible values:
##   - "Hmd":      stay in front of your Hmd
##   - "Absolute": fixed place in VR space
##   - "Sticky":   like "Absolute" but the overlay is repositionable
mode = "Hmd"

## how far away should the overlay be placed
## only meaningful if mode is "Hmd" or "Sticky"
distance = 0.75

## transformation matrix for absolute position, column-major
## only meaningful if mode is "Absolute"
# transform = [ [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1] ]

[display_mode]
## the display mode.
## possible values:
##   - "Stereo": show a 3D image, how much you can see is limited by how
##               big the overlay is in your field of view.
##   - "Flat":   show a flat image
mode = "Stereo"

## which camera's image to display in Flat mode
## only meaningful if mode is "Flat"
eye = "Left"

## Because your eyes and the cameras are at different physical locations, it is impossible
## to project camera view into VR space perfectly. There are trade offs approximating
## this projection.
##
## possible values:
## (a smaller viewing range here means things too close to you will give you double vision).
##
##   - "FromCamera": in this mode, we assume your eyes are at the cameras' physical location. this mode
##                   has larger viewing range, but everything will look smaller to you.
##   - "FromEye":    in this mode, we assume your cameras are at your eyes' physical location. everything will
##                   have the right scale in this mode, but the viewing range is smaller.
##
## only available if mode is "Stereo"
projection_mode = "FromEye"
